//CheckBox example
package assignmentt4_lab;
import java.awt.Font;
import javax.swing.*;
public class Task3
{
    public static void main(String[] args)
    {
        JFrame f = new JFrame();
        f.setBounds(100, 100, 700, 700);
        JLabel l1 = new JLabel("JSF 2 checkboxes example");
        Font font = new Font("SansSerif",Font.BOLD,30);
        l1.setBounds(0,0,400,400);
        l1.setFont(font);
        f.add(l1);
        
        JLabel l2 = new JLabel("1. Single checkbox");
        Font font1 = new Font("SansSerif",Font.BOLD,20);
        l2.setBounds(10, 100, 300, 300);
        l2.setFont(font1);
        JCheckBox c1 = new JCheckBox("Remember Me");
        c1.setBounds(10, 260, 120, 40);
        f.add(l2);
        f.add(c1);
        JLabel l3 = new JLabel("2. Multiple checkboxes");
        Font font2 = new Font("SansSerif",Font.BOLD,20);
        l3.setBounds(10, 170, 300, 300);
        l3.setFont(font2);
        f.add(l3);
        
        JLabel l4 = new JLabel("1. Hard-coded with \"fselecItem\":");
        Font font3 = new Font("Serif",Font.PLAIN,20);
        l4.setBounds(10, 200, 500, 300);
        l4.setFont(font3);
        JCheckBox c11 = new JCheckBox("Number1 - 1");
        c11.setBounds(10, 360, 100, 30);
        JCheckBox c22 = new JCheckBox("Number1 - 2");
        c22.setBounds(110, 360, 100, 30);
        JCheckBox c33 = new JCheckBox("Number1 - 3");
        c33.setBounds(220, 360, 100, 30);
        JCheckBox c44 = new JCheckBox("Number1 - 4");
        c44.setBounds(330, 360,        
 100, 30);
        JCheckBox c55 = new JCheckBox("Number1 - 5");
        c55.setBounds(440, 360, 100, 30);
        f.add(l4);
        f.add(c11);
        f.add(c22);
        f.add(c33);
        f.add(c44);
        f.add(c55);
        
        JLabel l5 = new JLabel("2. Generated by Array:");
        l5.setBounds(10, 260, 500, 300);
        l5.setFont(font3);
        JCheckBox c111 = new JCheckBox("Number2 - 1");
        c111.setBounds(10, 420, 100, 30);
        JCheckBox c222 = new JCheckBox("Number2 - 2");
        c222.setBounds(110, 420, 100, 30);
        JCheckBox c333 = new JCheckBox("Number2 - 3");
        c333.setBounds(220, 420, 100, 30);
        JCheckBox c444 = new JCheckBox("Number2 - 4");
        c444.setBounds(330, 420, 100, 30);
        JCheckBox c555 = new JCheckBox("Number2 - 5");
        c555.setBounds(440, 420, 100, 30);
        f.add(l5);
        f.add(c111);
        f.add(c222);
        f.add(c333);
        f.add(c444);
        f.add(c555);
        
        JLabel l6 = new JLabel("3. Generated by Map:");
        l6.setBounds(10, 320, 500, 300);
        l6.setFont(font3);
        JCheckBox c1111 = new JCheckBox("Number3 - 1");
        c1111.setBounds(10, 480, 100, 30);
        JCheckBox c2222 = new JCheckBox("Number3 - 2");
        c2222.setBounds(110, 480, 100, 30);
        JCheckBox c3333 = new JCheckBox("Number3 - 3");
        c3333.setBounds(220, 480, 100, 30);
        JCheckBox c4444 = new JCheckBox("Number3 - 4");
        c4444.setBounds(330, 480, 100, 30);
        JCheckBox c5555 = new JCheckBox("Number3 - 5");
        c5555.setBounds(440, 480, 100, 30);
        f.add(l6);
        f.add(c1111);
        f.add(c2222);
        f.add(c3333);
        f.add(c4444);
        f.add(c5555);
        
        
        
        JLabel l7 = new JLabel("4. Generated by Object with var:");
        l7.setBounds(10, 380, 500, 300);
        l7.setFont(font3);
        JCheckBox c11111 = new JCheckBox("Number4 - 1");
        c11111.setBounds(10, 540, 100, 30);
        JCheckBox c22222 = new JCheckBox("Number4 - 2");
        c22222.setBounds(110, 540, 100, 30);
        JCheckBox c33333 = new JCheckBox("Number4 - 3");
        c33333.setBounds(220, 540, 100, 30);
        JCheckBox c44444 = new JCheckBox("Number4 - 4");
        c44444.setBounds(330, 540, 100, 30);
        JCheckBox c55555 = new JCheckBox("Number4 - 5");
        c55555.setBounds(440, 540, 100, 30);
        f.add(l7);
        f.add(c11111);
        f.add(c22222);
        f.add(c33333);
        f.add(c44444);
        f.add(c55555);
        
        
        JButton submit_btn = new JButton("Submit");
        submit_btn.setBounds(10, 580, 80, 30);
        f.add(submit_btn);
        
        JButton reset_btn = new JButton("Reset");
        reset_btn.setBounds(100, 580, 70, 30);
        f.add(reset_btn);
        
        
        f.setLayout(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}