//RadioButton example
package assignmentt4_lab;

import java.awt.Font;
import javax.swing.*;

public class Task2
{
    public static void main(String[] args)
    {
        JFrame f = new JFrame();
        f.setBounds(100, 100, 700, 700);
        JLabel l1 = new JLabel("JSF 2 radio button example");
        Font font = new Font("SansSerif",Font.BOLD,30);
        l1.setBounds(0,0,400,400);
        l1.setFont(font);
        f.add(l1);
        
        JLabel l2 = new JLabel("1. Hard-coded with \"fselecItem\":");
        Font font1 = new Font("Serif",Font.ROMAN_BASELINE,20);
        l2.setBounds(10, 100, 300, 300);
        l2.setFont(font1);
        JRadioButton r1 = new JRadioButton("Color1 - Red");
        r1.setBounds(20, 260, 100, 40);
        JRadioButton r2 = new JRadioButton("Color1 - Green");
        r2.setBounds(150, 260, 120, 40);
        JRadioButton r3 = new JRadioButton("Color1 - Blue");
        r3.setBounds(280, 260, 100, 40);
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(r1);
        bg1.add(r2);
        bg1.add(r3);
        
        f.add(l2);
        f.add(r1);
        f.add(r2);
        f.add(r3);
        
        JLabel l3 = new JLabel("2. Generated by Map:");
        //Font font2 = new Font("SansSerif",Font.ROMAN_BASELINE,20);
        l3.setBounds(10, 170, 300, 300);
        l3.setFont(font1);
        JRadioButton r11 = new JRadioButton("Color2 - Red");
        r11.setBounds(20, 330, 100, 40);
        JRadioButton r22 = new JRadioButton("Color2 - Green");
        r22.setBounds(150, 330, 120, 40);
        JRadioButton r33 = new JRadioButton("Color2 - Blue");
        r33.setBounds(280, 330, 100, 40);
        
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(r11);
        bg2.add(r22);
        bg2.add(r33);
        
        f.add(l3);
        f.add(r11);
        f.add(r22);
        f.add(r33);
        
        JLabel l4 = new JLabel("3. Generated by Object array and iterate with var:");
        //Font font3 = new Font("SansSerif",Font.ROMAN_BASELINE,20);
        l4.setBounds(10, 240, 500, 300);
        l4.setFont(font1);
        JRadioButton r111 = new JRadioButton("Color3 - Red");
        r111.setBounds(20, 400, 100, 40);
        JRadioButton r222 = new JRadioButton("Color3 - Green");
        r222.setBounds(150, 400, 120, 40);
        JRadioButton r333 = new JRadioButton("Color3 - Blue");
        r333.setBounds(280, 400, 100, 40);
        
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(r111);
        bg3.add(r222);
        bg3.add(r333);
        
        f.add(l4);
        f.add(r111);
        f.add(r222);
        f.add(r333);
        
        JButton submit_btn = new JButton("Submit");
        submit_btn.setBounds(10, 450, 80, 30);
        f.add(submit_btn);
        
        JButton reset_btn = new JButton("Reset");
        reset_btn.setBounds(100, 450, 70, 30);
        f.add(reset_btn);
        
        f.setLayout(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
}
