//Listbox example
package assignmentt4_lab;
import java.awt.Font;
import javax.swing.*;
public class Task4
{
    public static void main(String[] args)
    {
        JFrame f = new JFrame();
        f.setBounds(100, 100, 700, 700);
        JLabel l1 = new JLabel("JSF 2 Listbox example");
        Font font = new Font("Serif",Font.BOLD,30);
        l1.setBounds(0,0,400,400);
        l1.setFont(font);
        f.add(l1);
        
        
        JLabel l2 = new JLabel("1. Hard-coded with \"fselecItem\":");
        Font font1 = new Font("Serif",Font.PLAIN,15);
        l2.setBounds(10, 150, 500, 300);
        l2.setFont(font1);
        DefaultListModel list1 = new DefaultListModel();
        list1.addElement("Year1 - 2000");
        list1.addElement("Year1 - 2010");
        list1.addElement("Year1 - 2020");
        JList<String> lb1 = new JList(list1);
        lb1.setBounds(210,230,100,80);
        f.add(l2);
        f.add(lb1);
        
        
        JLabel l3 = new JLabel("2. Generated by Map:");
        l3.setBounds(10, 240, 500, 300);
        l3.setFont(font1);
        DefaultListModel list2 = new DefaultListModel();
        list2.addElement("Year2 - 2000");
        list2.addElement("Year2 - 2010");
        list2.addElement("Year2 - 2020");
        JList<String> lb2 = new JList(list2);
        lb2.setBounds(150,320,100,80);
        f.add(l3);
        f.add(lb2);
       
        
        JLabel l4 = new JLabel("3. Generated by Object array and iterate with var:");
        l4.setBounds(10, 330, 500, 300);
        l4.setFont(font1);
        DefaultListModel list3 = new DefaultListModel();
        list3.addElement("Year3 - 2000");
        list3.addElement("Year3 - 2010");
        list3.addElement("Year3 - 2020");
        JList<String> lb3 = new JList(list3);
        lb3.setBounds(310,410,100,80);
        f.add(l4);
        f.add(lb3);
        
        JButton submit_btn = new JButton("Submit");
        submit_btn.setBounds(10, 500, 80, 30);
        f.add(submit_btn);
        
        JButton reset_btn = new JButton("Reset");
        reset_btn.setBounds(100, 500, 70, 30);
        f.add(reset_btn);
        
        
        f.setLayout(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }
}